/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/BalanceCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TransactionItem`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/format-data`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/create` | `/create`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/BalanceCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TransactionItem`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/format-data`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/create` | `/create`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/BalanceCard${`?${string}` | `#${string}` | ''}` | `/../components/TransactionItem${`?${string}` | `#${string}` | ''}` | `/../utils/format-data${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/BalanceCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TransactionItem`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/format-data`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/create` | `/create`; params?: Router.UnknownInputParams; };
    }
  }
}
